"""fix relations

Revision ID: e59fca8d9687
Revises: 982bf2c7a8fd
Create Date: 2025-09-02 07:23:36.038358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59fca8d9687'
down_revision = '982bf2c7a8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qtd', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unit_value', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('operation_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('brokerage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'])

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qtd', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('average_price', sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column('pl', sa.Numeric(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'])

    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_value', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'asset', ['asset_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('brokerage', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('brokerage')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('unit_value')
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pl')
        batch_op.drop_column('average_price')
        batch_op.drop_column('qtd')
        batch_op.drop_column('asset_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('brokerage')
        batch_op.drop_column('operation_type')
        batch_op.drop_column('unit_value')
        batch_op.drop_column('qtd')
        batch_op.drop_column('asset_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
